name: PHPUnit
on: ["push", "pull_request"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: MilesChou/composer-action/7.2/install@master
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        args: install --prefer-dist --ignore-platform-reqs    
    - name: PHPUnit
      run: docker run --rm -v $(pwd):/code domw/phpunit:7.2 phpunit Test
