name: PHPUnit
on: ["push", "pull_request"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: MilesChou/composer-action@master
      with:
        args: install    
    - name: PHPUnit
      run: docker run --rm -v $(pwd):/code domw/phpunit:latest phpunit Test
